#!/bin/bash

mkdir "$(pwd)/.folderwatch"

fwdir="$(pwd)/.folderwatch"
# echo "$fwdir"

pipename="$1"
if [[ -z "$1" ]]; then
	read -p "enter pipe name: " pipename
fi
mkfifo "$fwdir/$pipename"

echo "starting inotify daemon"

inotifywait -d -e create "$(pwd)" -o "$(pwd)/.folderwatch/$pipename" --timefmt "%a, %d %b %Y %T %z" --format "%e,%f"

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# echo "$DIR"
cp "$DIR/listener" "$fwdir/listener"
cp "$DIR/event" "$fwdir/event"
cp "$DIR/createDaemon" "$fwdir/createDaemon"
cp "$DIR/startListener" "$fwdir/startListener"

"$fwdir/startListener $pipename"
